### ISSUE TITLE
Iexec explorer not showing correct task times

### ISSUE THREAD

**Issue by borgqueenx** [iExecBlockchainComputing/iexec-core#348]
![Screenshot_20191225-191008_Samsung Internet](https://user-images.githubusercontent.com/20416925/71449321-43655900-274a-11ea-8041-27c01c5af55b.jpg)
See the image.
Time of tasks are not in correct order, and are also sometimes on a time thats later then the current time.
Hopefully the site can show times based on the user device/browser and that the bug about time can be fixed some time^^

**Comment by PierreJeanjacquot** [comment]
Hi @borgqueenx,
Sorry for the late answer, I hope this will be useful:
- Time displayed is the task deadline in your local time (after this time the task can't be completed and can be claimed) that's why this time may be in the future.
- Tasks are ordered by update time (last updated first, each status change is an update).
